### ISSUE TITLE
Does this package support AMD CPU?

### ISSUE THREAD

**Issue by takfate** [rocm-arch/rocm-arch#513]
sorry. I have a question: does this package support `AMD CPU`?
Because I saw the `mkl` is likely in the build log..
And I have the following error when compiling.
```
[3647/4636] cd /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH && /usr/bin/cmake -E make_directory /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/./torch_hip_generated_THHTensorIndex.hip.o -P /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/torch_hip_generated_THHTensorIndex.hip.o.cmake
ninja: build stopped: subcommand failed.
Building wheel torch-1.7.1
-- Building version 1.7.1
cmake -GNinja -DBUILD_BINARY=ON -DBUILD_CUSTOM_PROTOBUF=OFF -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/torch -DCMAKE_PREFIX_PATH=/usr/lib/python3.8/site-packages -DCUDNN_INCLUDE_DIR=/usr/include -DCUDNN_LIBRARY=/usr/lib -DDISABLE_AVX2=1 -DDISABLE_AVX512F=1 -DDISABLE_FMA4=1 -DDISABLE_SSE4=1 -DNUMPY_INCLUDE_DIR=/usr/lib/python3.8/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python3.8 -DPYTHON_LIBRARY=/usr/lib/libpython3.8.so.1.0 -DTORCH_BUILD_VERSION=1.7.1 -DUSE_CUDA=OFF -DUSE_FFMPEG=ON -DUSE_GFLAGS=ON -DUSE_GLOG=ON -DUSE_MKLDNN=ON -DUSE_NUMPY=True -DUSE_ROCM=ON -DUSE_SYSTEM_NCCL=ON /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm
cmake --build . --target install --config Release -- -j 16
Traceback (most recent call last):
  File "setup.py", line 760, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 349, in build
    self.run(build_args, my_env)
  File "/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by acxz** [comment]
@takfate we have quite a few packages in rocm-arch. Can you mention which one you asking about?
