### ISSUE TITLE
[rocblas] `Kernels.o` no such file (build error)

### ISSUE THREAD

**Issue by acxz** [rocm-arch/rocm-arch#660]
I got the following error when building rocblas.

```
Generating kernels: Done.
35355it [00:00, 1041549.85it/s]
Compiling source kernels: Launching 12 threads...
/opt/rocm/llvm/bin/clang-offload-bundler: error: '/home/acxz/.cache/yay/rocblas/src/build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.o': No such file or directory
clang-14: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/Parallel.py", line 51, in apply_print_exception
    return func(*args)
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 200, in buildSourceCodeObjectFile
    subprocess.check_call(compileArgs)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/hipcc', '--genco', '-D__HIP_HCC_COMPAT_MODE__=1', '-I', '/home/acxz/.cache/yay/rocblas/src/build/Tensile', '--offload-arch=gfx803', '--offload-arch=gfx900', '--offload-arch=gfx906:xnack-', '--offload-arch=gfx908:xnack-', '--offload-arch=gfx90a:xnack+', '--offload-arch=gfx90a:xnack-', '--offload-arch=gfx1010', '--offload-arch=gfx1011', '--offload-arch=gfx1012', '--offload-arch=gfx1030', '/home/acxz/.cache/yay/rocblas/src/build/Tensile/Kernels.cpp', '-c', '-o', '/home/acxz/.cache/yay/rocblas/src/build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.o']' returned non-zero exit status 1.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/Parallel.py", line 51, in apply_print_exception
    return func(*args)
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 200, in buildSourceCodeObjectFile
    subprocess.check_call(compileArgs)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/hipcc', '--genco', '-D__HIP_HCC_COMPAT_MODE__=1', '-I', '/home/acxz/.cache/yay/rocblas/src/build/Tensile', '--offload-arch=gfx803', '--offload-arch=gfx900', '--offload-arch=gfx906:xnack-', '--offload-arch=gfx908:xnack-', '--offload-arch=gfx90a:xnack+', '--offload-arch=gfx90a:xnack-', '--offload-arch=gfx1010', '--offload-arch=gfx1011', '--offload-arch=gfx1012', '--offload-arch=gfx1030', '/home/acxz/.cache/yay/rocblas/src/build/Tensile/Kernels.cpp', '-c', '-o', '/home/acxz/.cache/yay/rocblas/src/build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.o']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/acxz/.cache/yay/rocblas/src/build/library/src/../../virtualenv/lib/python3.10/site-packages/Tensile/bin/TensileCreateLibrary", line 38, in <module>
    TensileCreateLibrary()
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 1469, in TensileCreateLibrary
    codeObjectFiles = writeSolutionsAndKernels(outputPath, CxxCompiler, problemTypes, solutions,
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 546, in writeSolutionsAndKernels
    codeObjectFiles += buildSourceCodeObjectFiles(CxxCompiler, kernelFiles, outputPath)
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/TensileCreateLibrary.py", line 254, in buildSourceCodeObjectFiles
    coFiles = Common.ParallelMap(buildSourceCodeObjectFile, args, "Compiling source kernels",
  File "/home/acxz/.cache/yay/rocblas/src/build/virtualenv/lib/python3.10/site-packages/Tensile/Parallel.py", line 122, in ParallelMap
    rv = mapFunc(function, objects)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command '['/usr/bin/hipcc', '--genco', '-D__HIP_HCC_COMPAT_MODE__=1', '-I', '/home/acxz/.cache/yay/rocblas/src/build/Tensile', '--offload-arch=gfx803', '--offload-arch=gfx900', '--offload-arch=gfx906:xnack-', '--offload-arch=gfx908:xnack-', '--offload-arch=gfx90a:xnack+', '--offload-arch=gfx90a:xnack-', '--offload-arch=gfx1010', '--offload-arch=gfx1011', '--offload-arch=gfx1012', '--offload-arch=gfx1030', '/home/acxz/.cache/yay/rocblas/src/build/Tensile/Kernels.cpp', '-c', '-o', '/home/acxz/.cache/yay/rocblas/src/build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.o']' returned non-zero exit status 1.
make[2]: *** [library/src/CMakeFiles/TENSILE_LIBRARY_TARGET.dir/build.make:91: Tensile/library/TensileLibrary.yaml] Error 1
make[2]: Leaving directory '/home/acxz/.cache/yay/rocblas/src/build'
make[1]: *** [CMakeFiles/Makefile2:257: library/src/CMakeFiles/TENSILE_LIBRARY_TARGET.dir/all] Error 2
make[1]: Leaving directory '/home/acxz/.cache/yay/rocblas/src/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/home/acxz/.cache/yay/rocblas/src/build'
```

If someone has compiled it successfully do you mind just sending over the `*.zst` file to me?

**Comment by tpkessler** [comment]
Hey @acxz! I've compiled `rocblas` successfully. What's your preferred way to receive the compiled package from me?

**Comment by acxz** [comment]
hmm not sure, maybe you can just sent a google drive link?

**Comment by tpkessler** [comment]
I sent you a link.

**Comment by acxz** [comment]
Closing this issue for now, since it seems like a me problem. If I encounter this when I try to build rocblas again, I'll post a discussions post.
