### ISSUE TITLE
Core dump in polaris with rocm opencl version 6.0

### ISSUE THREAD

**Issue by BishopWolf** [rocm-arch/rocm-arch#981]
Following the discussion here https://github.com/Oblomov/clinfo/issues/95

```
$ gdb --args clinfo
GNU gdb (GDB) 14.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from clinfo...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /usr/bin/clinfo
(No debugging symbols found in clinfo)                                                                                                   
(gdb) run
Starting program: /usr/bin/clinfo 
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc6000                                                                
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4processes-92d9f07e.so         
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4geometry-0c687114.so          
Downloading separate debug info for /opt/rocm/lib/libOpenCL.so.1                                                                         
Downloading separate debug info for /usr/lib/libdl.so.2                                                                                  
Downloading separate debug info for /usr/lib/libc.so.6       
[Thread debugging using libthread_db enabled]                                                                                            
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Downloading separate debug info for /usr/lib/libexpat.so.1
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4analysis-58c18685.so          
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4digits_hits-49ed91d8.so       
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4track-0f17a637.so             
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4materials-0a3fe0e7.so         
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4zlib-8a92f4d5.so              
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4particles-a2ab1706.so         
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4graphics_reps-f3db01e8.so     
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4intercoms-d770af8d.so         
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4global-a19c55f2.so            
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4clhep-170e676c.so             
Downloading separate debug info for /home/alex/.local/lib/python3.11/site-packages/opengate_core.libs/libG4ptl-124ac18e.so.2.3.3         
Downloading separate debug info for /usr/lib/libm.so.6                                                                                   
Downloading separate debug info for /usr/lib/libpthread.so.0                                                                             
Downloading separate debug info for /opt/rocm/lib/libamdocl64.so                                                                         
Downloading separate debug info for /opt/rocm/lib/libamd_comgr.so.2                                                                      
Downloading separate debug info for /opt/rocm/lib/libhsa-runtime64.so.1                                                                  
Downloading separate debug info for /usr/lib/libnuma.so.1                                                                                
Downloading separate debug info for /usr/lib/libz.so.1                                                                                   
Downloading separate debug info for /usr/lib/libzstd.so.1                                                                                
Downloading separate debug info for /usr/lib/libncursesw.so.6                                                                            
Downloading separate debug info for /opt/rocm/lib/libhsakmt.so.1                                                                         
Downloading separate debug info for /usr/lib/libelf.so.1                                                                                 
Downloading separate debug info for /usr/lib/libdrm.so.2                                                                                 
Downloading separate debug info for /usr/lib/libdrm_amdgpu.so.1                                                                          
[New Thread 0x7fffe9bff6c0 (LWP 839783)]                                                                                                 
[New Thread 0x7fffe93fe6c0 (LWP 839784)]
free(): invalid pointer
[Thread 0x7fffe93fe6c0 (LWP 839784) exited]

Thread 1 "clinfo" received signal SIGABRT, Aborted.
0x00007ffff5aab32c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5aab32c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff5a5a6c8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff5a424b8 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff5a43395 in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff5ab52a7 in ?? () from /usr/lib/libc.so.6
#5  0x00007ffff5ab75b4 in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff5ab9e93 in free () from /usr/lib/libc.so.6
#7  0x00007ffff48aeaba in operator delete (ptr=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/del_op.cc:49
#8  0x00007ffff48aeaea in operator delete[] (ptr=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/del_opv.cc:35
#9  0x00007ffff451faad in roc::Device::~Device (this=<optimized out>, this=<optimized out>)
    at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/rocclr/device/rocm/rocdevice.cpp:279
#10 0x00007ffff45a127d in roc::Device::~Device (this=<optimized out>, this=<optimized out>)
    at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/rocclr/device/rocm/rocdevice.cpp:290
#11 std::default_delete<roc::Device>::operator() (__ptr=0x5555556f43a0, this=<optimized out>)
    at /usr/include/c++/13.2.1/bits/unique_ptr.h:99
#12 std::unique_ptr<roc::Device, std::default_delete<roc::Device> >::~unique_ptr (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/13.2.1/bits/unique_ptr.h:404
#13 roc::Device::init () at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/rocclr/device/rocm/rocdevice.cpp:530
#14 amd::Device::init () at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/rocclr/device/device.cpp:488
#15 amd::Runtime::init() [clone .isra.0] () at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/rocclr/platform/runtime.cpp:75
#16 0x00007ffff44ef2cd in std::once_flag::_Prepare_execution::_Prepare_execution<std::call_once<clIcdGetPlatformIDsKHR::{lambda()#1}>(std::once_flag&, clIcdGetPlatformIDsKHR::{lambda()#1}&&)::{lambda()#1}>(clIcdGetPlatformIDsKHR::{lambda()#1}&)::{lambda()#1}::_FUN() ()
    at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/opencl/amdocl/cl_icd.cpp:224
#17 0x00007ffff5aae6af in ?? () from /usr/lib/libc.so.6
#18 0x00007ffff44ef100 in __gthread_once (__func=<optimized out>, __once=0x7ffff45f2f70 <clIcdGetPlatformIDsKHR::initOnce>)
    at /usr/include/c++/13.2.1/x86_64-pc-linux-gnu/bits/gthr-default.h:700
#19 std::call_once<clIcdGetPlatformIDsKHR(cl_uint, _cl_platform_id**, cl_uint*)::<lambda()> > (__once=..., __f=...)
    at /usr/include/c++/13.2.1/mutex:907
#20 clIcdGetPlatformIDsKHR (num_entries=num_entries@entry=0, platforms=platforms@entry=0x0, 
    num_platforms=num_platforms@entry=0x7fffffffd4dc) at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/opencl/amdocl/cl_icd.cpp:274
#21 0x00007ffff7fb94d4 in khrIcdVendorAdd (libraryName=0x5555555eec20 "/opt/rocm/lib/libamdocl64.so")
    at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/opencl/khronos/icd/loader/icd.c:107
#22 0x00007ffff7fb9980 in khrIcdOsVendorsEnumerate ()
    at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/opencl/khronos/icd/loader/linux/icd_linux.c:129
#23 0x00007ffff5aae6af in ?? () from /usr/lib/libc.so.6
#24 0x00007ffff7fb9a45 in khrIcdOsVendorsEnumerateOnce ()
    at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/opencl/khronos/icd/loader/linux/icd_linux.c:163
#25 khrIcdInitialize () at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/opencl/khronos/icd/loader/icd.c:35
#26 clGetPlatformIDs (num_entries=0, platforms=0x0, num_platforms=0x7fffffffd630)
    at /usr/src/debug/rocm-opencl-runtime/clr-rocm-6.0.0/opencl/khronos/icd/loader/icd_dispatch.c:38
#27 0x000055555555b1e6 in ?? ()
#28 0x00007ffff5a43cd0 in ?? () from /usr/lib/libc.so.6
#29 0x00007ffff5a43d8a in __libc_start_main () from /usr/lib/libc.so.6
#30 0x000055555555b8be in ?? ()
(gdb) Quit

```

**Comment by rastarr** [comment]
is there any update, fix or workaround on this issue?
